# Generated by Django 4.2.3 on 2024-03-30 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'categorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('mono', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(default='India', max_length=150)),
                ('zipcode', models.CharField(max_length=150)),
                ('totalprice', models.FloatField()),
                ('status', models.CharField(choices=[('Out For Shipping', 'Out For Shipping'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150)),
                ('payment_mode', models.CharField(max_length=150)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'order',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subcategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'subcategorie',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='productinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField(max_length=500)),
                ('totalqty', models.IntegerField(default=None)),
                ('availableqty', models.IntegerField(default=None)),
                ('op', models.IntegerField(default=None)),
                ('dp', models.IntegerField(default=None)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=trending')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesmartlookapp.categorie')),
                ('size', models.ManyToManyField(to='thesmartlookapp.size')),
                ('subcategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesmartlookapp.subcategorie')),
            ],
            options={
                'verbose_name_plural': 'productinfo',
                'ordering': ('categorie', 'subcategorie', 'name'),
            },
        ),
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesmartlookapp.order')),
                ('productinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesmartlookapp.productinfo')),
            ],
            options={
                'verbose_name_plural': 'orderitems',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contactus',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psize', models.CharField(default=None, max_length=5)),
                ('pqty', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesmartlookapp.productinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart',
                'ordering': ('user',),
            },
        ),
    ]
